### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by nickpalladino** [IntegratedBreedingPlatform/BMSAPI#256]
In the readme section for code contributing developers, a few of the links for getting everything setup don't work. This includes the link for the BMSConfig repo and a link to setuputils for getting a BMS development environment setup. Is this still the procedure or has something changed?

**Comment by nahuel-soldevilla** [comment]
@nickpalladino 

We've modified the README file to point to a new page: https://github.com/IntegratedBreedingPlatform/Documentation/wiki/Manual-setup, which has instructions on how to build BMS from source. A new public repo was created: https://github.com/IntegratedBreedingPlatform/bms-config-template/ which contains template files with properties needed to build BMS and some example defaults.
The Middleware project also now contains a clean database that you can work with: https://github.com/IntegratedBreedingPlatform/Middleware/pull/735 
Please give it a try when you can and let us know if there's something still missing.

Thanks.

cc @mcrimi @clarysabel @abatac
